### PR TITLE
G4.62 Add a message processor method to validator GermplasmNameExists

### LINKED ISSUE #62: G4.62 Create a process messages method for GermplasmNameExists
### Branch

g4.62-GermplasmNameExistsProcessor

### Groups

Group 4 - API | Services | Plugins

### Describe

The `GermplasmNameExists` validator currently doesn't have a method that will process messages for display to the user during failed validation. As part of the tasks for issue #59, this issue will focus on adding a processor method to the GermplasmNameExists validator class in particular.

### Design

The processor method will follow the same design used for the `ProjectGenusMatch` validator in PR https://github.com/TripalCultivate/TripalCultivate-Phenotypes/pull/159.

Additionally, we will want to consider creating a test importer so that process methods for validators in the TripalCultivate module can be manually tested (since currently, there are no importers implemented in this module).

### PR DESCRIPTION
**Pull request by carolyncaron**
**Issue #62**

## Motivation
The `GermplasmNameExists` validator currently doesn't have a method that will process messages for display to the user during failed validation.

The processor method will follow the same design used for the `ProjectGenusMatch` validator in PR https://github.com/TripalCultivate/TripalCultivate-Phenotypes/pull/159.

## What does this PR do?
- [x] Creates a new process method `processListWithDescribedTable`
- [x] Creates a new class for automated testing the process method: `ValidatorGermplasmNameExistsProcessTest.php`
- [x] Defines the new $mapping property for validators in `TripalCultivateValidatorBase`
- [x] Creates 2 new helper methods than can be generically used by other validators/importer in service `ImportValidationHelper`
   - `fillTableGaps`: For filling in gaps in tables meant to be rendered with an empty string
   - `renderSimpleWarningMessage`: Given a message as a string, produces a render array of type "markup" for displaying the string.
- [x] ~~Adds a test importer to the module so that manual testing of the validators can take place~~  UPDATE: This is now being done by PR #66 

### Automated Testing

**ValidatorGermplasmNameExistsProcessTest.php**:
- `testProcessListWithDescribedTable`: tests processListWithDescribedTable() with failed cases for missing and/or duplicate germplasm.
   - A germplasm name cell is missing from the database
   - A germplasm name cell is duplicated in the database
   - Within one row, 1 cell has missing germplasm, and 1 has a duplicate
   - Test for both duplicate and missing germplasm on multiple rows and in multiple columns.
   - Test for [contact-admin] token in the case of a duplicate germplasm.
   - Customize both the missing and duplicate case messages.
   - Provide a custom case message with default + custom tokens

- `testProcessListWithDescribedTableEmptyCell`: tests processListWithDescribedTable() with failed cases for empty germplasm name cells
   - A single germplasm name cell is empty
   - Multiple empty germplasm name cells
   - An empty germplasm name cell, a missing germplasm, and a duplicate.
   - An empty cell and a token to replace the entire displayed message.

- `testProcessListWithDescribedTableExceptions`: tests processListWithDescribedTable() with scenarios that are expected to trigger an exception.
   - Case of an empty germplasm name cell, but an invalid message is passed in using the token for case-empty-germplasm. This exception gets triggered in `renderSimpleWarningMessage()`
   - GermplasmNameExists passed validation.
   - Unrecognizable validation case message.

**ServiceImportValidationHelperTest.php**:
- `testFillTableGaps`: tests fillTableGaps() with scenarios for different tables.
   - A simple table with no gaps.
   - A table that has a gap in the middle of one row.
   - A table with gaps at both edges of a row.
   - A complex table with multiple gaps on multiple rows.
   - An unsorted table with gaps.

-`testRenderSimpleWarningMessage`: tests renderSimpleWarningMessage()
   - Triggers the exception that occurs when message is an empty string.
   - Gives a regular message string and pulls out the rendered message using the default class `simple-validation-warning` and 2 custom classes.
   - Confirms that no table is being rendered by this method. 

### Manual Testing

1. Start a fresh docker image/container on this branch. **You can use the devcontainer approach OR the following commands:**
  ```
  cd ~/Dockers
  git clone https://github.com/TripalCultivate/TripalCultivate g4.62-GermplasmNameExistsProcessor
  cd g4.62-GermplasmNameExistsProcessor
  git checkout g4.62-GermplasmNameExistsProcessor
  docker build --tag=trpcultivate-base:review63 ./
  docker run --publish=80:80 -tid --name=base63 --volume=`pwd`:/var/www/drupal/web/modules/contrib/TripalCultivate trpcultivate-base:review63
  ```

2. Navigate to your site and login. Create a new organism using whatever genus and species you like.
3. Download the following zipped archive, unzip and place `TestTripalImporter.php` into the following directory on this branch (you will need to create the `TripalImporter` directory in `Plugin`): `/var/www/drupal/web/modules/contrib/TripalCultivate/src/Plugin/TripalImporter`

   - [TestGermplasmNameExists.zip](https://github.com/user-attachments/files/20891502/TestGermplasmNameExists.zip)

4. Clear the cache, then navigate to `Admin > Tripal > Data Loaders > Tripal Cultivate: Test Importer`
5. Upload the file `TestGermName.tsv` and Import
6. You should see the resulting screenshot below:
Screenshot 2025-06-24 at 2 18 52 PM

7. You can tweak `TestGermName.tsv` to try testing different variations of an input file. Alternatively, you can copy one of the first parameters (validation results) from any of the data providers in `/tests/src/Kernel/Validators/ValidatorGermplasmNameExistsProcessTest.php` and paste it in `TestTripalImporter.php` on line 245 (an example is already provided inside a comment). Make sure the array is assigned to `$failures[$id]` and adjust `$metadata` and `$tokens` as needed. This will overwrite whatever is in your test file - you will still need to upload one to trigger the validation.

### CODE REVIEW

File: src/Plugin/Validators/GermplasmNameExists.php [hunk 1]
```diff
@@ -201,4 +251,198 @@ public function validateRow($row_values) {
...
+    // NOTE: Dependency injection is NOT used since this is a static method.
+    $service_TripalTokensParser = \Drupal::service('tripal.token_parser');
+    // Grab the default messages for all of our tokens (ones with default-msg).
+    $default_tokens = array_column(self::$mapping, 'default-msg', 'token');
+    // Combine our provided and our default token arrays. Because array_merge
+    // will overwrite values in the first array with values from the second
+    // array for the same keys, we provide our default tokens first.
+    $combined_tokens = array_merge($default_tokens, $tokens);
+
+    // For this validator there are can be up to 2 tables:
```
Comment (reynoldtan) [inline src/Plugin/Validators/GermplasmNameExists.php]:
```suggestion
    // For this validator there can be up to 2 tables:
```

File: src/Plugin/Validators/GermplasmNameExists.php [hunk 2]
```diff
@@ -201,4 +251,198 @@ public function validateRow($row_values) {
...
+      ImportValidationHelper::checkValidationStatusArray($validation_status, 'GermplasmNameExists', $line_no);
+
+      // If any cells were found to be empty, this case takes presendence over
+      // any other cases, and we return a warning message right away.
+      if ($validation_status['case'] == 'Unable to lookup germplasm with empty values') {
+        // Add a token for the column header names of the germplasm columns.
+        $combined_tokens['column-headers'] = implode(', ', $metadata['column_headers']);
+        $message = $service_TripalTokensParser->replaceTokens($combined_tokens['case-empty-germplasm'], $combined_tokens);
+        return ImportValidationHelper::renderSimpleWarningMessage($message, ['tc-germplasm-name-exists-empty']);
+      }
```
Comment (reynoldtan) [inline src/Plugin/Validators/GermplasmNameExists.php]: With this intended presedence, in the validateRow() where this if condition is in a foreach loop
```
foreach(....) {
  if (!isset($cell) || empty($cell)) {
    $empty = TRUE;
    $failedItems['empty_cells'][] = $index;
  }
}

...

if ($empty) {
  return [
    'case' => 'Unable to lookup germplasm with empty values',
    'valid' => FALSE,
    'failedItems' => $failedItems,
   ];
}
````
can be revised to the following without the need to complete the foreach loop and return the warning message right away

````
// Stop on first instance of empty germplasm.
if (!isset($cell) || empty($cell)) {
  return [
    'case' => 'Unable to lookup germplasm with empty values',
    'valid' => FALSE,
    'failedItems' => headers containing germplasm names,
  ];
}
```

The variable $failedItems['empty_cells'][] = $index; is also unecessary since failedItem is always the headers selected to contain the germplasm.

File: tests/src/Kernel/Validators/ValidatorGermplasmNameExistsProcessTest.php [hunk 3]
```diff
@@ -0,0 +1,857 @@
...
+          'expected_rows' => [
+            5 => [
+              'Paternal Parent' => 'Duplicate Germplasm',
+            ],
+          ],
+        ],
+      ],
+    ];
+
+    // #3: Test for both duplicate and mssign germplasm on multiple rows and in
```
Comment (reynoldtan) [inline tests/src/Kernel/Validators/ValidatorGermplasmNameExistsProcessTest.php]:
```suggestion
    // #3: Test for both duplicate and missing germplasm on multiple rows and in
```

**Comment by reynoldtan** [comment]
**It is impressive!** 👏  Just this one observation that if a column in a datafile has an empty string for germplasm, the warning message below is displayed and no further details.

image

File: src/Plugin/Validators/GermplasmNameExists.php [hunk 4]
```diff
@@ -201,4 +251,198 @@ public function validateRow($row_values) {
...
+   *   - The 'title' is a sentence describing the case triggered
+   *   - The 'items' include a table for each potential case in the $failures
+   *     array:
+   *     - If a germplasm name is empty
+   *       - Headers include 'Row Number', 'Column Header'
+   *     - A duplicate germplasm name seen in the database
+   *       - Headers include 'Row Number', 'Column Header', 'Germplasm Name'
+   *     - A missing germplasm name from the database
+   *       - Headers include 'Row Number', 'Column Header', 'Germplasm Name'
+   *
```
Comment (laceysanderson) [inline src/Plugin/Validators/GermplasmNameExists.php]: This description feels at odds with what is actually returned to me since there is no 'title' and it doesn't mention the 'block' that we discussed in person. 

It turns out that my suggestion to reynold for this type of array doesn't translate as well to multiple tables as I had hoped 🙈 That said, what about something like:

> A render array of type "unordered list" used to display feedback to the user about the validation failure, where each item is a markup block containing:
> - A message describing the case triggered
> - A table that lists the row and column combinations with failures for this case
>
> Note that each case triggered with have it's own markup block. The table headers for each case are:
> - Germplasm name is empty: 'Row Number', 'Column Header'.
> - A duplicate germplasm name seen in the database: 'Row Number', 'Column Header', 'Germplasm Name'.
> - A missing germplasm name from the database: 'Row Number', 'Column Header', 'Germplasm Name'.

File: src/Plugin/Validators/GermplasmNameExists.php [hunk 5]
```diff
@@ -37,6 +38,55 @@ class GermplasmNameExists extends TripalCultivateValidatorBase implements Contai
...
+   *  - 'case-duplicate-germplasm': the message when a germplasm name is
+   *    duplicated in the database.
+   *
+   * @see TripalCultivate/src/TripalCultivateValidator/TripalCultivateValidatorBase::$mapping
+   */
+  protected static array $mapping = [
+    'case-empty-germplasm' => [
+      'token' => 'case-empty-germplasm',
+      'dev-case' => 'Unable to lookup germplasm with empty values',
+      'default-msg' => 'One or more cells which are expected to contain germplasm names was empty. Please ensure that you have non-empty cells for the following columns: [column-headers]',
```
Comment (laceysanderson) [inline src/Plugin/Validators/GermplasmNameExists.php]: Should we make it clear they are required? I would be tempted to reword this:

> One or more cells which are required to contain germplasm names were empty. Please ensure that you have entered existing germplasm names for all cells in the following columns: [column-headers]'

**Comment by vidu-wil** [comment]
All the automated and the manual tests provided work as expected. I also did the testing indicated on step 7 of manual testing (with and without tokens) as shown below and it looks great! 
Screenshot 2025-07-09 at 9 30 59 AM
Screenshot 2025-07-09 at 10 33 39 AM
Screenshot 2025-07-09 at 10 44 29 AM

File: src/Plugin/Validators/GermplasmNameExists.php [hunk 6]
```diff
@@ -37,6 +38,55 @@ class GermplasmNameExists extends TripalCultivateValidatorBase implements Contai
...
+    ],
+    'case-missing-germplasm' => [
+      'token' => 'case-missing-germplasm',
+      'dev-case' => 'Missing germplasm name(s) in the database',
+      'default-msg' => 'The following germplasm names could not be found in the database.',
```
Comment (laceysanderson) [inline src/Plugin/Validators/GermplasmNameExists.php]: Maybe talking about the database is too techie? What about something like:

> The following germplasm names do not match any existing in this site. Please make sure you have entered the names exactly as they appear on the germplasm pages or [contact-admin] to have them added if they do not yet exist.

File: src/Plugin/Validators/GermplasmNameExists.php [hunk 7]
```diff
@@ -37,6 +38,55 @@ class GermplasmNameExists extends TripalCultivateValidatorBase implements Contai
...
+    ],
+    'case-duplicate-germplasm' => [
+      'token' => 'case-duplicate-germplasm',
+      'dev-case' => 'Duplicate(s) found in the database for germplasm name(s)',
+      'default-msg' => 'The following germplasm names have 2 or more records in the database associated with them. Please resolve the duplications or [contact-admin] for help with investigating.',
```
Comment (laceysanderson) [inline src/Plugin/Validators/GermplasmNameExists.php]: We should be clear that they should resolve it IN THEIR FILE so they don't try to fix our site if they have permission :see_no_evil: What about something like:

> The following germplasm names in your file have been duplicated in this site (i.e. there are two pages for the same germplasm). If there is a more specific germplasm already existing in the site then use that in your file. Regardless, [contact-admin] to have the duplications resolved in the site.

File: src/Plugin/Validators/GermplasmNameExists.php (hunk 4 above)
Comment (laceysanderson) [reply src/Plugin/Validators/GermplasmNameExists.php]: Still unresolved.

File: src/Plugin/Validators/GermplasmNameExists.php [hunk 8]
```diff
@@ -201,4 +251,198 @@ public function validateRow($row_values) {
...
+          $table[$case]['rows'] = [];
+        }
+        // Define a new row in our table for this line number.
+        $table[$case]['rows'][$line_no][-1] = $line_no;
+        // For each index with an failed germplasm, grab the column name from
+        // $metadata and add it to our table header.
+        foreach ($validation_status['failedItems'][$case] as $index => $germplasm) {
+          // Grab the column name based on the index of the germplasm
+          // and add it to this table header if it's not already there.
+          $column_name = $metadata['column_headers'][$index];
```
Comment (laceysanderson) [inline src/Plugin/Validators/GermplasmNameExists.php:412]: This is passed in by the developer but we're not actually validating it anywhere, are we? Perhaps we should at least check the index exists here and throw a good error if it doesn't?

File: src/Service/ImportValidationHelper.php [hunk 9]
```diff
@@ -274,4 +274,82 @@ public static function checkValidationStatusArray(array $validation_result, stri
     return TRUE;
   }
 
+  /**
+   * Take an array with table contents and fill empty cells with empty strings.
```
Comment (laceysanderson) [inline src/Service/ImportValidationHelper.php]: I think it's more correct to refer to these as missing cells that we are adding empty cells for. :thinking:

> Fill missing cells in table rows with empty cells.

File: src/Service/ImportValidationHelper.php [hunk 10]
```diff
@@ -274,4 +274,82 @@ public static function checkValidationStatusArray(array $validation_result, stri
...
+   *
+   * @param array $table
```
Comment (laceysanderson) [inline src/Service/ImportValidationHelper.php]: I actually expected this to be a table render array but instead it looks like your custom arrays you create before the render array? If this is the case, I'd be tempted to either use the full render array OR pass in the header array and rows array as two separate params. That way no one will assume it's a full table render array.

File: src/Service/ImportValidationHelper.php [hunk 11]
```diff
@@ -274,4 +274,82 @@ public static function checkValidationStatusArray(array $validation_result, stri
...
+      }
+    }
+  }
+
+  /**
+   * A helper method that will process any simple message into a render array.
+   *
+   * @param string $message
+   *   A non-empty string that is the message to be displayed to the user. If
+   *   desired, this string may include css formatting.
```
Comment (laceysanderson) [inline src/Service/ImportValidationHelper.php]: It's more that it can include HTML, right?
```suggestion
   *   A non-empty string that is the message to be displayed to the user. If
   *   desired, this string may include HTML tags.
```

File: src/Service/ImportValidationHelper.php [hunk 12]
```diff
@@ -274,4 +274,82 @@ public static function checkValidationStatusArray(array $validation_result, stri
...
+   * @param array $classes
+   *   [OPTIONAL] An array of strings to give to '#wrapper_attributes' of the
+   *   render array as a set of css classed. By default, this method adds the
```
Comment (laceysanderson) [inline src/Service/ImportValidationHelper.php]:
```suggestion
   *   [OPTIONAL] An array of strings to give to '#wrapper_attributes' of the
   *   render array as a set of css classes. By default, this method adds the
```

File: src/TripalCultivateValidator/TripalCultivateValidatorBase.php [hunk 13]
```diff
@@ -21,6 +21,42 @@ abstract class TripalCultivateValidatorBase extends PluginBase implements Tripal
    */
   protected array $context = [];
 
+  /**
+   * A mapping array that maps tokens to their details for a validator.
+   *
+   * This mapping starts with all of the potential cases for a validator,
+   * followed by additional tokens which are subsitutable within the message(s)
```
Comment (laceysanderson) [inline src/TripalCultivateValidator/TripalCultivateValidatorBase.php]:
```suggestion
   * followed by additional tokens which are substitutable within the message(s)
```

File: src/TripalCultivateValidator/TripalCultivateValidatorBase.php [hunk 14]
```diff
@@ -21,6 +21,42 @@ abstract class TripalCultivateValidatorBase extends PluginBase implements Tripal
...
+   *   number of smaller, non case-specific tokens contained in square brackets.
+   *   For example:
+   *     "The selected [project] does not exist. Please [contact-admin] to have
+   *     this added." where both [project] and [contact-admin] are separate
+   *     non case-specific tokens (see definition of remaining tokens below).
+   *
+   * NOTE: The token 'case-valid' is reserved for the valid case for this
+   * validator, and does NOT have a corresponding default message. Although
+   * uncommon, when there is more than one valid case, assign 'case-valid' to
+   * the most common passed case, and suffix `case-valid' with more details for
```
Comment (laceysanderson) [inline src/TripalCultivateValidator/TripalCultivateValidatorBase.php:48]: I think it's the prefix 'case-valid' not the suffix, right?

File: src/TripalCultivateValidator/TripalCultivateValidatorBase.php [hunk 15]
```diff
@@ -21,6 +21,42 @@ abstract class TripalCultivateValidatorBase extends PluginBase implements Tripal
...
+   * the other(s).
+   *
+   * For all remaining tokens, the array key is the substitutable token, with
+   * the following key-pairs:
+   * - 'token': the substitutable text in a message. This text would become
+   *   flanked by brackets within a message string. For eg. [token]
+   * - 'default-msg': A string that would substitute the associated token
+   *   within a case message.
```
Comment (laceysanderson) [inline src/TripalCultivateValidator/TripalCultivateValidatorBase.php]:
```suggestion
   * - 'default-msg': A string that would substitute the associated token
   *   elsewhere in the render array (e.g. within the case message).
```

**Review by laceysanderson — CHANGES_REQUESTED** [review]
We should add tests to the ImportValidationHelper test class for these methods. I know they are tested indirectly through this validator but specific, generic tests would be better to ensure the cells are actually in the arrays and what-not.

File: src/TripalCultivateValidator/TripalCultivateValidatorBase.php (hunk 14 above)
Comment (carolyncaron) [reply src/TripalCultivateValidator/TripalCultivateValidatorBase.php:48]: Correct, suffix here is being used as a verb 😅

File: src/Plugin/Validators/GermplasmNameExists.php (hunk 2 above)
Comment (carolyncaron) [reply src/Plugin/Validators/GermplasmNameExists.php]: Thanks for pointing this out! I've added a @todo to deal with this if we ever need a performance boost in commit [cc92b0f](https://github.com/TripalCultivate/TripalCultivate/pull/63/commits/cc92b0f8e353f6b00b1f65f43fbff060ff94df8c)

File: src/Plugin/Validators/GermplasmNameExists.php (hunk 5 above)
Comment (carolyncaron) [reply src/Plugin/Validators/GermplasmNameExists.php]: Agreed, it should be more clear! Addressed in commit https://github.com/TripalCultivate/TripalCultivate/pull/63/commits/119bd33a5472a737d06562e79fbcb9ee326b1529

File: src/Plugin/Validators/GermplasmNameExists.php (hunk 6 above)
Comment (carolyncaron) [reply src/Plugin/Validators/GermplasmNameExists.php]: Addressed in commit https://github.com/TripalCultivate/TripalCultivate/pull/63/commits/119bd33a5472a737d06562e79fbcb9ee326b1529!

File: src/Plugin/Validators/GermplasmNameExists.php (hunk 7 above)
Comment (carolyncaron) [reply src/Plugin/Validators/GermplasmNameExists.php]: Addressed in commit https://github.com/TripalCultivate/TripalCultivate/pull/63/commits/119bd33a5472a737d06562e79fbcb9ee326b1529!

File: src/Plugin/Validators/GermplasmNameExists.php (hunk 4 above)
Comment (carolyncaron) [reply src/Plugin/Validators/GermplasmNameExists.php]: Addressed in commit https://github.com/TripalCultivate/TripalCultivate/pull/63/commits/c1e68aa4a226ce41f0bcc5ab71b3f6b626bd2277

File: src/Plugin/Validators/GermplasmNameExists.php (hunk 8 above)
Comment (carolyncaron) [reply src/Plugin/Validators/GermplasmNameExists.php:412]: Good catch! Addressed in commit https://github.com/TripalCultivate/TripalCultivate/pull/63/commits/2ffb73ad0e8403d4b788fcd0b9942433445e9360

File: src/Service/ImportValidationHelper.php (hunk 9 above)
Comment (carolyncaron) [reply src/Service/ImportValidationHelper.php]: Addressed in commit https://github.com/TripalCultivate/TripalCultivate/pull/63/commits/d4bc00f86afc940dae02e174f2ef05350155af52

File: src/Service/ImportValidationHelper.php (hunk 10 above)
Comment (carolyncaron) [reply src/Service/ImportValidationHelper.php]: Yes, it's on the custom array. I opted for header and rows as separate params, change was made in commit https://github.com/TripalCultivate/TripalCultivate/pull/63/commits/d4bc00f86afc940dae02e174f2ef05350155af52

**Review by laceysanderson — DISMISSED** [review]
All of my previous comments have been resolved and the new tests look great! I think this is ready to merge!!! 🎉

File: src/Plugin/Validators/GermplasmNameExists.php [hunk 16]
```diff
@@ -37,6 +38,55 @@ class GermplasmNameExists extends TripalCultivateValidatorBase implements Contai
...
+      'dev-case' => 'Missing germplasm name(s) and found duplicate(s) in the database',
+    ],
+    'case-valid' => [
+      'token' => 'case-valid',
+      'dev-case' => 'Germplasm name(s) exist(s) in the database',
+    ],
+    'contact-admin' => [
+      'token' => 'contact-admin',
+      'default-msg' => 'contact your administrator',
+    ],
```
Comment (reynoldtan) [inline src/Plugin/Validators/GermplasmNameExists.php:89]: https://github.com/TripalCultivate/TripalCultivate/blob/d1b13fb26129e71ad5502d6254bb1ada1e25bf69/src/Plugin/Validators/GermplasmNameExists.php#L361
Kindly define the token used in the $mapping array and briefly document in the docblock for the $mapping.
```
'column-headers' => [
  'token' => 'column-headers'
]
```

Comment (laceysanderson) [reply src/Plugin/Validators/GermplasmNameExists.php:89]: Additionally we discussed having a comment above the definition/docs for these programatically determined token ensuring that developers know they cannot override the value of this token.

This gets to a missing test case that we may want to add which is that an incorrect `column-headers` token is passed into the process method. The test would confirm that the one passed in is not used but rather is overridden by the value determined within the method.

Comment (carolyncaron) [reply src/Plugin/Validators/GermplasmNameExists.php:89]: Addressed in commits https://github.com/TripalCultivate/TripalCultivate/pull/63/commits/98fc15e77db83a4152d4196361a74a2dd3d82da8 and https://github.com/TripalCultivate/TripalCultivate/pull/63/commits/bad43d97a5b6769f5de0549d4f9f8169d6953f06

NOTE: I realized that based on the current implementation, a developer could still use the 'column-headers' token and it would apply for custom messages in cases other than empty cell. I'm okay with this, since the $mapping array docblock now warns developers against this, but I'm not sure if you both would agree 😅

Comment (carolyncaron) [reply src/Plugin/Validators/GermplasmNameExists.php:89]: Alternatively, I could move the logic of assigning the column header names to the top of the method, that way if a developer wants to use it in a custom message for ANY of the cases, they can. And the statement that "it cannot be overridden" would then be true in all cases, which should cause less potential confusion.

Comment (carolyncaron) [reply src/Plugin/Validators/GermplasmNameExists.php:89]: Implemented widespread use of column-headers token in commit https://github.com/TripalCultivate/TripalCultivate/pull/63/commits/5bdc451eb32b22a94426131e8a3c59515fa51011

**Review by laceysanderson — APPROVED** [review]
Updates related to the 'column-headers' token look good 👍 I'm glad you moved the setting to the top of the method so it can be used in non-empty cell messages and the added test ensuring that a developer passed version of this token does not override the real value looks perfect :-) I also like the added bit to an existing scenario making sure this token can be used in non-empty cell cases <3
