### PR TITLE
G4.68 Empty Cell validator process message

### LINKED ISSUE #67: G4.167 - Implement process message method into validators
### Branch

g4.167-ValidatorProcessMessage

### Groups

Group 4 - API | Services | Plugins

### Describe

Using ProjectGenusMatch validator as reference, implement a process message into validators.

### Design

To Implement process message.

1. Setup the mapping array for tokens and messages.
2. Implement the static process message class
 - The method for this step can be copied from the Traits Importer in TripalCultivate-Phenotypes.
 - Remove each process for each validator
4. Setup a test file for the the process message.
- The test class for this step can be copied from TripalCultivate-Phenotypes/tests/src/TripalImporter/TraitImporterProcessValidationTest.

For example: 

Image

NOTES:
- Additional will be the exception message test for each validator.
- After migrating each process test cases from the file, delete the main process test file?

Validators and cases:

**EmptyCell**

- [x] [case-empty-value]: Empty value found in required column(s)
- [x] [case-valid]: No empty values found in required column(s) **(PASS)**

**Germplasm Name Exists** (in progress - see PR #63) 

- [x] [case-empty-germplasm]: Unable to lookup germplasm with empty values
- [x] [case-missing-germplasm]: Missing germplasm name(s) in the database
- [x] [case-missing-duplicate-gemplasm]: Missing germplasm name(s) and found duplicate(s) in the database
- [x] [case-duplicate-germplasm]: Duplicate(s) found in the database for germplasm name(s)
- [x] [case-valid]: Germplasm name(s) exist(s) in the database (PASS)

**Project Exists**

- [x] [case-project-nonexistent]: Project does not exist **(case-project-absent)** **(case-no-project)**
- [x] [case-valid]: Project exists **(PASS)**

**Valid Data File**

- [x] [case-invalid-file]: Invalid file id number **(case-invalid-fid)**
- [x] [case-failed-fid]: File id failed to load a file object
- [x] [case-empty-file]: The file has no data and is an empty file
- [x] [case-unsupported-mime]: Unsupported file MIME type
- [x] [case-unsupported-mime-extension]: Unsupported file mime type and unsupported extension **(case-unsupported-extension)**
- [x] [case-locked-file]: Data file cannot be opened
- [x] [case-valid]: Data file is valid **(PASS)**

**Valid Delimited File**

- [x] [case-empty-row]: Raw row is empty
- [x] [case-no-delimiter-used]: None of the delimiters supported by the file type was used **(case-no-delimiter)**
- [x] [case-exceeding-column-number]: Raw row exceeds number of strict columns **(case-too-many-columns)** **(case-excess-columns)**
- [x] [case-insufficient-column-number]: Raw row has insufficient number of columns **(case-missing-columns)** **(case-insufficient-columns)**
- [x] [case-valid-singlecol]: Raw row has expected number of columns **(PASS)** @todo check that this case only happens when it's a single column.
- [x] [case-valid]: Raw row is delimited **(PASS)**

**Valid Headers**

- [x] [case-empty-headers]: Header row is an empty value
- [x] [case-mismatch-headers]: Headers do not match expected headers **(case-mismatch-values)**
- [x] [case-unexpected-headers-count]: Headers provided does not have the expected number of headers **(case-mismatch-count)**
- [x] [case-valid]: Headers exist and match expected headers **(PASS)**

**Value In List**

- [x] [case-invalid-column-value]: Invalid value(s) in required column(s) **(case-invalid-value)**
- [x] [case-invalid-column-value-case-match]: Invalid value(s) in required column(s) with >=1 case insensitive match **(case-insensitive-match)** **(case-invalid-lettercase-mismatch)**
- [x] [case-valid]: Values in required column(s) are valid **(PASS)**

### PR DESCRIPTION
**Pull request by reynoldtan**
**Issue #67 Implement process message into validators**

## Motivation

Implement process message method into validators:

- [x] EmptyCell

## What does this PR do?

Code reference to version in Traits Importer: https://github.com/TripalCultivate/TripalCultivate-Phenotypes/blob/b5b0450bb086e1318b5854394c2de1873bc40ef4/trpcultivate_phenotypes/src/Plugin/TripalImporter/TripalCultivatePhenotypesTraitsImporter.php#L1257
- Implement process message to validator
- Setup a test for the process message

### Automated Testing

Execute tests to ensure continuous success of tests for EmptyCell validator.
Test files in TripalCultivate/tests/src/Kernel/Validators:
1. ValidatorEmptyCellTest.php
2. ValidatorEmptyCellProcessTest.php

### Manual Testing

1. Start a fresh docker image/container on this branch. **You can use the devcontainer approach OR the following commands:**
  ```
  cd ~/Dockers
  git clone https://github.com/TripalCultivate/TripalCultivate trpcultBase-PRNUM
  git checkout BRANCHNAME
  cd trpcultBase-PRNUM
  docker build --tag=trpcultivate-base:reviewPRNUM ./
  docker run --publish=80:80 -tid --name=basePRNUM --volume=`pwd`:/var/www/drupal/web/modules/contrib/TripalCultivate trpcultivate-base:reviewPRNUM
  ```
4. In devel/php, use the code snippet below to inspect the rendered process message.

```
// Empty Cell:
$validator_id = 'empty_cell';
$validator = \Drupal::service('plugin.manager.trpcultivate_validator')
  ->createInstance($validator_id);

// Setup parameters: $failurs, $headers and $tokens.
$failures = [
  [
    'case' => 'Empty value found in required column(s)',
    'valid' => FALSE,
    'failedItems' => [
      'empty_indices' => [0], // Column Header 1 is empty
    ],
  ],
];

$headers = [
  [
    'name' => 'Header 1',
    'type' => 'required',
  ],
  [
    'name' => 'Header 2',
    'type' => 'required',
  ]
];

$tokens = [];

// Method call
$process_message = $validator::processListWithDescribedTable($failures, $headers, $tokens);
dpm($process_message, 'raw render array');

$render = \Drupal::service('renderer')->render($process_message);
dpm($render, 'rendered render array');
```

Using test importer
1. Download and extract the package below into src/Plugin/TripalImporter directory of your clone site.
[TestTripalImporter.zip](https://github.com/user-attachments/files/21021163/TestTripalImporter.zip)

2. Clear cache
3. Access the importer localhost/admin/tripal/loaders/trpcultivate-test-importer
4. Upload the provided tsv file.

### CODE REVIEW

File: src/Plugin/Validators/EmptyCell.php [hunk 1]
```diff
@@ -78,12 +104,137 @@ public function validateRow($row_values) {
...
+   *   - 'project': the word to use when referring to the project.
+   *   - 'contact-admin': the phrase to use when the user needs a privileged
+   *     administrator to fix the problem.
+   *   The following token keys will substitute the entire existing case message
+   *   to the user with the value of that token.
+   *   - 'case-no-project': the message when a project does not exist.
+   *   - 'case-no-paired-genus': the message when a project has no genus set
+   *     to it.
+   *   - 'case-project-genus-mismatch': the message when the genus selected
+   *     by the user is not configured to the selected project.
```
Comment (carolyncaron) [inline src/Plugin/Validators/EmptyCell.php]: Remember to update this for EmptyCell 😄

File: src/Plugin/Validators/EmptyCell.php [hunk 2]
```diff
@@ -78,12 +104,137 @@ public function validateRow($row_values) {
...
+   *   and column combinations with empty cells. It has the following headers:
+   *   - 'Line Number'
+   *   - 'Column(s) with empty value'
+   *
+   * @throws \Exception
+   *   - If the validation_result parameter was not formatted properly.
+   *   - If the case string returned by the validator implied validation passed.
+   *   - If the case string returned by the validator is not recognized.
+   */
+  public static function processListWithDescribedTable(array $failures, array $headers, array $tokens = []) {
```
Comment (carolyncaron) [inline src/Plugin/Validators/EmptyCell.php]: Instead of passing the parameter $headers, you should be using $metadata instead. This will allow us to provide additional information to headers in the future if needed without expanding the param list for the method.

See here for the definition of $metadata (you can copy and paste this 😉 ): https://github.com/TripalCultivate/TripalCultivate/blob/3080d00180b0b7fb250ed38c36dd665c2d64c7f6/src/Plugin/Validators/GermplasmNameExists.php#L303-L312

```suggestion
  public static function processListWithDescribedTable(array $failures, array $tokens = [], array $metadata) {
```

File: tests/src/Kernel/Validators/ValidatorEmptyCellProcessTest.php [hunk 3]
```diff
@@ -0,0 +1,465 @@
...
+   *   - 'expected_message': The message expected in the return value of the
+   *       process method for this scenario.
+   *   - 1+ arrays keyed by the line number in the input file that triggered
+   *     the failed validation status, further keyed by:
+   *     - 'expected_columns': A comma-separated list of column headers that
+   *       map to the expected columns with empty values.
+   *
+   * @dataProvider provideEmptyCellFailedCases
+   */
+  public function testProcessEmptyCellFailures(array $failures, array $expectations) {
```
Comment (carolyncaron) [inline tests/src/Kernel/Validators/ValidatorEmptyCellProcessTest.php]: The name should be more specific to account for potential future process methods.
```suggestion
  public function testProcessListWithDescribedTable(array $failures, array $expectations) {
```

File: tests/src/Kernel/Validators/ValidatorEmptyCellProcessTest.php [hunk 4]
```diff
@@ -0,0 +1,465 @@
...
+   *         - 'valid': FALSE to indicate that validation failed.
+   *         - 'failedItems': array of items that failed consistent with the
+   *           validator in this scenario.
+   *   - 'expected_message': The expected exception message to be triggered
+   *     by the case message that is not recognized by the process validation
+   *     method for this validator.
+   *
+   * @dataProvider providePassedAndUnrecognizableCases
+   */
+  public function testProcessFailuresExceptions(string $process_method, array $passed_case, array $unrecognized_case) {
```
Comment (carolyncaron) [inline tests/src/Kernel/Validators/ValidatorEmptyCellProcessTest.php]:
```suggestion
  public function testProcessListWithDescribedTableExceptions(string $process_method, array $passed_case, array $unrecognized_case) {
```

File: tests/src/Kernel/Validators/ValidatorEmptyCellProcessTest.php [hunk 5]
```diff
@@ -0,0 +1,465 @@
...
+
+    // Test with a passed validation case string.
+    $exception_caught = FALSE;
+    $exception_message = 'NONE';
+
+    try {
+      call_user_func_array([$this->validator_instance, $process_method], $passed_case['process_method_params']);
```
Comment (carolyncaron) [inline tests/src/Kernel/Validators/ValidatorEmptyCellProcessTest.php]: Using `call_user_func_array` is no longer necessary now that we know exactly which process method we are testing. 😊 You can see what I did for ProjectGenusMatch for how to simplify both the method and its data provider:

https://github.com/TripalCultivate/TripalCultivate-Phenotypes/blob/b5b0450bb086e1318b5854394c2de1873bc40ef4/trpcultivate_phenotypes/tests/src/Kernel/Validators/ValidatorProjectGenusMatchProcessTest.php#L326-L437

**Review by carolyncaron — COMMENTED** [review]
Just a reminder that you shouldn't tackle the following validators _in this PR_:
- `GermplasmNameExists` (this is being done in PR #63)
- `ProjectExists` (this is not needed by the Pheno Share Importer and can be revisited at a later time)

Here are my comments for EmptyCell so far!

File: src/Plugin/Validators/EmptyCell.php (hunk 1 above)
Comment (reynoldtan) [reply src/Plugin/Validators/EmptyCell.php]: Good catch! revised in https://github.com/TripalCultivate/TripalCultivate/pull/68/commits/504fe430e45a550eabe1d576a9460ab0da3a36dd

File: tests/src/Kernel/Validators/ValidatorEmptyCellProcessTest.php (hunk 5 above)
Comment (reynoldtan) [reply tests/src/Kernel/Validators/ValidatorEmptyCellProcessTest.php]: Revised in https://github.com/TripalCultivate/TripalCultivate/pull/68/commits/4e03ffe518b0bcb684d3db9c4330bd1299a573c4

File: src/Plugin/Validators/EmptyCell.php [hunk 6]
```diff
@@ -24,6 +25,31 @@ class EmptyCell extends TripalCultivateValidatorBase {
    */
   use ColumnIndices;
 
+  /**
+   * A mapping of all of the tokens supported by this validator.
+   *
+   * @var array
+   *   An associative array mapping tokens to their details where each element
+   *   may contain a default message but must contain the dev-case and token.
```
Comment (carolyncaron) [inline src/Plugin/Validators/EmptyCell.php]: This is no longer technically correct 🙈 Here is what I put for `GermplasmNameExists`: 
```suggestion
   *   An associative array mapping tokens to their details, such as the
   *   developer case string and the default message to substitute the token.
```

File: src/Plugin/Validators/EmptyCell.php [hunk 7]
```diff
@@ -78,12 +104,136 @@ public function validateRow($row_values) {
...
+   *   An associative array that stores the validation failures by the
+   *   EmptyCell validator. It is keyed by the line number of the input
+   *   file where validation failed, and the value is an associative array
+   *   returned by the validator. Here is the overall structure of $failures:
+   *   - [LINE NUMBER]:
+   *     - 'case': a developer-focused string describing the case checked.
+   *     - 'valid': FALSE to indicate that validation failed.
+   *     - 'failedItems': an array of items that failed:
+   *       - 'empty_indices': A list of column indices in the line which were
+   *         checked and found to be empty.
```
Comment (carolyncaron) [inline src/Plugin/Validators/EmptyCell.php]: For consistency with `GermplasmNameExists` and to avoid repetition, I suggest:
```suggestion
   *     - 'failedItems': an array of items that failed, where the key => value
   *       pairs map to the index => cell value(s) that failed validation.
   *       @see EmptyCell::validateRow()
```

File: src/Plugin/Validators/EmptyCell.php [hunk 8]
```diff
@@ -78,12 +104,136 @@ public function validateRow($row_values) {
...
+   *           '4' => 'Header 4', // Header of column #5
+   *         ].
+   *
+   * @return array
+   *   A render array of type unordered list which is used to display feedback
+   *   to the user about the case(s) that failed and the failed items from the
+   *   input file. This unordered list will include a table that lists the row
+   *   and column combinations with empty cells. It has the following headers:
+   *   - 'Line Number'
+   *   - 'Column(s) with empty value'
```
Comment (carolyncaron) [inline src/Plugin/Validators/EmptyCell.php]: Just another suggestion to make this doc consistent with `GermplasmNameExists`:

```suggestion
   *   A render array of type "unordered list" used to display feedback to the
   *   user about the validation failure, where:
   *   - The 'title' is a sentence describing the case triggered
   *   - The 'items' include a table that lists the row and column combinations
   *     with empty cells. It has the following headers:
   *     - 'Line Number'
   *     - 'Column(s) with empty value'
```

File: src/Plugin/Validators/EmptyCell.php [hunk 9]
```diff
@@ -78,12 +104,136 @@ public function validateRow($row_values) {
...
+   *
+   * @throws \Exception
+   *   - If the validation_result parameter was not formatted properly.
+   *   - If the case string returned by the validator implied validation passed.
+   *   - If the case string returned by the validator is not recognized.
+   */
+  public static function processListWithDescribedTable(array $failures, array $tokens = [], array $metadata = []) {
```
Comment (carolyncaron) [inline src/Plugin/Validators/EmptyCell.php]: As per our chat with Lacey, we're going to standardize the first parameter for row-level validator processors to be `$validation_results`:
```suggestion
  public static function processListWithDescribedTable(array $validation_results, array $tokens = [], array $metadata = []) {
```

File: src/Plugin/Validators/EmptyCell.php [hunk 10]
```diff
@@ -78,12 +104,136 @@ public function validateRow($row_values) {
...
+   * @return array
+   *   A render array of type unordered list which is used to display feedback
+   *   to the user about the case(s) that failed and the failed items from the
+   *   input file. This unordered list will include a table that lists the row
+   *   and column combinations with empty cells. It has the following headers:
+   *   - 'Line Number'
+   *   - 'Column(s) with empty value'
+   *
+   * @throws \Exception
+   *   - If the validation_result parameter was not formatted properly.
```
Comment (carolyncaron) [inline src/Plugin/Validators/EmptyCell.php]:
```suggestion
   *   - If a validation status array was not formatted properly.
```

File: src/Plugin/Validators/EmptyCell.php [hunk 11]
```diff
@@ -78,12 +104,136 @@ public function validateRow($row_values) {
...
   }
 
+  /**
+   * Processes failed validation from EmptyCell into a render array.
+   *
+   * @param array $failures
+   *   An associative array that stores the validation failures by the
+   *   EmptyCell validator. It is keyed by the line number of the input
+   *   file where validation failed, and the value is an associative array
+   *   returned by the validator. Here is the overall structure of $failures:
```
Comment (carolyncaron) [inline src/Plugin/Validators/EmptyCell.php]:
```suggestion
   * @param array $validation_results
   *   An associative array that stores the validation failures by the
   *   EmptyCell validator. It is keyed by the line number of the input
   *   file where validation failed, and the value is an associative array
   *   returned by the validator. Here is the overall structure:
```

File: src/Plugin/Validators/EmptyCell.php [hunk 12]
```diff
@@ -78,12 +104,136 @@ public function validateRow($row_values) {
...
+    // array for the same keys, we provide our default tokens first.
+    $combined_tokens = array_merge($default_tokens, $tokens);
+
+    foreach ($failures as $line_no => $validation_result) {
+      // Check the format of the validation_result parameter.
+      ImportValidationHelper::checkValidationStatusArray($validation_result, 'EmptyCell', $line_no);
+
+      if ($validation_result['case'] == self::$mapping['case-empty-value']['dev-case']) {
+        // Convert indices in failedItems to column headers.
+        $failed_indices = $validation_result['failedItems']['empty_indices'];
```
Comment (carolyncaron) [inline src/Plugin/Validators/EmptyCell.php]:
```suggestion
    foreach ($validation_results as $line_no => $validation_status) {
      // Check the format of the validation_status parameter.
      ImportValidationHelper::checkValidationStatusArray($validation_status, 'EmptyCell', $line_no);

      if ($validation_status['case'] == self::$mapping['case-empty-value']['dev-case']) {
        // Convert indices in failedItems to column headers.
        $failed_indices = $validation_status['failedItems']['empty_indices'];
```

File: src/Plugin/Validators/EmptyCell.php [hunk 13]
```diff
@@ -78,12 +104,136 @@ public function validateRow($row_values) {
...
+        }
+        // Implode the empty headers array into a string and then add it as a
+        // row to our table.
+        $columns_string = implode(", ", $empty_headers);
+        array_push($table['rows'], [
+          $line_no,
+          $columns_string,
+        ]);
+      }
+      elseif ($validation_result['case'] == self::$mapping['case-valid']['dev-case']) {
```
Comment (carolyncaron) [inline src/Plugin/Validators/EmptyCell.php]:
```suggestion
      elseif ($validation_status['case'] == self::$mapping['case-valid']['dev-case']) {
```

File: tests/src/Kernel/Validators/ValidatorEmptyCellProcessTest.php [hunk 14]
```diff
@@ -0,0 +1,452 @@
...
+   *   - 'expected_message': The message expected in the return value of the
+   *       process method for this scenario.
+   *   - 1+ arrays keyed by the line number in the input file that triggered
+   *     the failed validation status, further keyed by:
+   *     - 'expected_columns': A comma-separated list of column headers that
+   *       map to the expected columns with empty values.
+   *
+   * @dataProvider provideEmptyCellFailedCases
+   */
+  public function testProcessListWithDescribedTable(array $failures, array $tokens, array $metadata, array $expectations) {
```
Comment (carolyncaron) [inline tests/src/Kernel/Validators/ValidatorEmptyCellProcessTest.php]: This will also need to updated in the docs and in the code 😅 
```suggestion
  public function testProcessListWithDescribedTable(array $validation_results, array $tokens, array $metadata, array $expectations) {
```

File: tests/src/Kernel/Validators/ValidatorEmptyCellProcessTest.php [hunk 15]
```diff
@@ -0,0 +1,452 @@
...
+   *         - 'valid': FALSE to indicate that validation failed.
+   *         - 'failedItems': array of items that failed consistent with the
+   *           validator in this scenario.
+   *   - 'expected_message': The expected exception message to be triggered
+   *     by the case message that is not recognized by the process validation
+   *     method for this validator.
+   *
+   * @dataProvider providePassedAndUnrecognizableCases
+   */
+  public function testProcessListWithDescribedTableExceptions(array $passed_case, array $unrecognized_case) {
```
Comment (carolyncaron) [inline tests/src/Kernel/Validators/ValidatorEmptyCellProcessTest.php]: This test can be simplified to only half the code by passing in the passed case and the unrecognizable case as 2 separate scenarios. See: https://github.com/TripalCultivate/TripalCultivate-Phenotypes/blob/b5b0450bb086e1318b5854394c2de1873bc40ef4/trpcultivate_phenotypes/tests/src/Kernel/Validators/ValidatorProjectGenusMatchProcessTest.php#L412-L435

File: tests/src/Kernel/Validators/ValidatorEmptyCellProcessTest.php [hunk 16]
```diff
@@ -0,0 +1,452 @@
...
+   *   - An array of expectations that we want to find in the resulting rendered
+   *     output which has the following keys:
+   *     - 'expected_message': The message expected in the return value of the
+   *       process method for this scenario.
+   *     - 1+ arrays keyed by the line number in the input file that triggered
+   *       the failed validation status, further keyed by:
+   *       - 'expected_columns': A comma-separated list of column headers that
+   *         map to the expected columns with empty values.
+   */
+  public static function provideEmptyCellFailedCases() {
```
Comment (carolyncaron) [inline tests/src/Kernel/Validators/ValidatorEmptyCellProcessTest.php:108]: You should add a test case here to make sure tokens are working. In this case, a test for substituting the message for 'case-empty-value'.

**Review by carolyncaron — CHANGES_REQUESTED** [review]
These are mostly suggestions to make the code consistent with `GermplasmNameExists`!

File: tests/src/Kernel/Validators/ValidatorEmptyCellProcessTest.php (hunk 5 above)
Comment (carolyncaron) [reply tests/src/Kernel/Validators/ValidatorEmptyCellProcessTest.php]: This method can still be simplified further - see my comment below!

File: src/Plugin/Validators/EmptyCell.php (hunk 7 above)
Comment (reynoldtan) [reply src/Plugin/Validators/EmptyCell.php]: The @see comment, should it not be just @see validateRow()? This notation EmptyCell::validateRow() tells me validateRow() is a static method which is not.

File: src/Plugin/Validators/EmptyCell.php (hunk 9 above)
Comment (reynoldtan) [reply src/Plugin/Validators/EmptyCell.php]: The standard was: $validation_status - validator in an input type (ie. file, metadata) with single response item and $validation_results - validator in an input type (ie. raw-row, data-raw) with one or more response items.

File: src/Plugin/Validators/EmptyCell.php (hunk 7 above)
Comment (carolyncaron) [reply src/Plugin/Validators/EmptyCell.php]: Just referring to validateRow() sounds good to me! 👍

File: tests/src/Kernel/Validators/ValidatorEmptyCellProcessTest.php (hunk 15 above)
Comment (reynoldtan) [reply tests/src/Kernel/Validators/ValidatorEmptyCellProcessTest.php]: Test is simplified in https://github.com/TripalCultivate/TripalCultivate/pull/68/commits/63f67a408d342b82d562239b907ef5c0adbf4032

File: tests/src/Kernel/Validators/ValidatorEmptyCellProcessTest.php (hunk 16 above)
Comment (reynoldtan) [reply tests/src/Kernel/Validators/ValidatorEmptyCellProcessTest.php:108]: Test case added in https://github.com/TripalCultivate/TripalCultivate/pull/68/commits/63f67a408d342b82d562239b907ef5c0adbf4032

File: tests/src/Kernel/Validators/ValidatorEmptyCellProcessTest.php [hunk 17]
```diff
@@ -0,0 +1,456 @@
...
+      $exception_caught = TRUE;
+      $exception_message = $e->getMessage();
+    }
+
+    $line = array_keys($validation_result);
+    $line = reset($line);
+
+    $this->assertTrue(
+      $exception_caught,
+      'We expected an exception to be caught ' . $validation_result[$line]['case'] . ', but one was not thrown.'
```
Comment (carolyncaron) [inline tests/src/Kernel/Validators/ValidatorEmptyCellProcessTest.php]:
```suggestion
      'We expected an exception to be caught for case ' . $validation_result[$line]['case'] . ', but one was not thrown.'
```

File: tests/src/Kernel/Validators/ValidatorEmptyCellProcessTest.php (hunk 16 above)
Comment (carolyncaron) [reply tests/src/Kernel/Validators/ValidatorEmptyCellProcessTest.php:108]: This looks great!

File: tests/src/Kernel/Validators/ValidatorEmptyCellProcessTest.php [hunk 18]
```diff
@@ -0,0 +1,456 @@
...
+   *             '4' => 'Header 2', // Header of column #5.
+   * @param array $expectations
+   *   An array of expectations in the rendered output which has the following
+   *   keys:
+   *   - 'expected_message': The exception message that is expected to be
+   *     triggered.
+   *
+   * @dataProvider providePassedAndUnrecognizableCases
+   */
+  public function testProcessListWithDescribedTableExceptions(array $validation_result, array $tokens, array $metadata, array $expectations) {
```
Comment (carolyncaron) [inline tests/src/Kernel/Validators/ValidatorEmptyCellProcessTest.php]:
```suggestion
  public function testProcessListWithDescribedTableExceptions(array $validation_results, array $tokens, array $metadata, array $expectations) {
```

File: tests/src/Kernel/Validators/ValidatorEmptyCellProcessTest.php [hunk 19]
```diff
@@ -0,0 +1,456 @@
...
+      ],
+    ];
+
+    return $scenarios;
+  }
+
+  /**
+   * Tests for exceptions thrown for passed and unrecognizable case strings.
+   *
+   * @param array $validation_result
```
Comment (carolyncaron) [inline tests/src/Kernel/Validators/ValidatorEmptyCellProcessTest.php]:
```suggestion
   * @param array $validation_results
```

File: tests/src/Kernel/Validators/ValidatorEmptyCellProcessTest.php (hunk 14 above)
Comment (carolyncaron) [reply tests/src/Kernel/Validators/ValidatorEmptyCellProcessTest.php]: It looks like this suggestion got missed! Remember to also update it in the doc

File: src/Plugin/Validators/EmptyCell.php [hunk 20]
```diff
@@ -78,12 +104,137 @@ public function validateRow($row_values) {
...
+    $service_TripalTokensParser = \Drupal::service('tripal.token_parser');
+    $replaced_message = $service_TripalTokensParser->replaceTokens($table['message'], $combined_tokens);
+
+    // Build the render array for our table.
+    $render_array = [
+      '#theme' => 'item_list',
+      '#type' => 'ul',
+      '#attributes' => [
+        'class' => [
+          'tcp-empty-cell-failures',
```
Comment (carolyncaron) [inline src/Plugin/Validators/EmptyCell.php]: Just noticed this one- EmptyCell is now in TripalCultivate 🙈 
```suggestion
          'tc-empty-cell-failures',
```

**Review by carolyncaron — CHANGES_REQUESTED** [review]
Looks great - just a couple of small suggestions! I think it's definitely safe to move onto the remaining process methods 😄

File: tests/src/Kernel/Validators/ValidatorEmptyCellProcessTest.php (hunk 15 above)
Comment (carolyncaron) [reply tests/src/Kernel/Validators/ValidatorEmptyCellProcessTest.php]: This is great!! Thanks Reynold!

File: src/Plugin/Validators/EmptyCell.php [hunk 21]
```diff
@@ -78,12 +104,137 @@ public function validateRow($row_values) {
...
+   *     contain a value.
+   *
+   * @return array
+   *   A render array of type "unordered list" used to display feedback to the
+   *   user about the validation failure, where:
+   *   - The 'title' is a sentence describing the case triggered
+   *   - The 'items' include a table that lists the row and column combinations
+   *     with empty cells. It has the following headers:
+   *     - 'Line Number'
+   *     - 'Column(s) with empty value'
```
Comment (laceysanderson) [inline src/Plugin/Validators/EmptyCell.php]: This description feels at odds with what is actually returned to me since there is no 'title' and it doesn't mention the 'block' that we discussed in person. What about something like:

> A render array of type "unordered list" used to display feedback to the user about the validation failure, where each item is a markup block containing:
> - A message describing the case triggered
> - A table that lists the row and column combinations with empty cells. It has the following headers:
>   - 'Line Number'
>   - 'Column(s) with empty value'

**Review by laceysanderson — COMMENTED** [review]
This is looking on track with my expectations/understanding 😍  The only thing that jumped out at me was the render array. I checked with Carolyns GermplasmNameExists and it looks like I need to suggest there as well. Does this get across better that its a list of blocks not just a list with the first element being a message and the second a table?

File: src/Plugin/Validators/EmptyCell.php (hunk 21 above)
Comment (reynoldtan) [reply src/Plugin/Validators/EmptyCell.php]: Applied in https://github.com/TripalCultivate/TripalCultivate/pull/68/commits/1a6d4116eb70854cf2879ace4923637eea5219c1

**Review by laceysanderson — APPROVED** [review]
Looks good to me!

**Review by carolyncaron — APPROVED** [review]
Looks like everything I brought up in my reviews have been addressed 👍
