### PR TITLE
Fix bug in createTestFile method of importer test trait

### LINKED ISSUE #58: [Bug] Test Trait createTestFiles() could not reference file fixture in Phenotypes
### Drupal Version

9.4

### Tripal Version

4.0.0-alpha1

### Module Version

4.x dev (most recent commit)

### Site Operating System

Debian Linux

### Installation Method

TripalDocker docker

### Browsers

_No response_

### Observations

The createTestFile() method could not reference file fixture in phenotypes.

### Expected Behaviour

Enable createTestFile() method to access file fixtures relative to the module it was called.

### Steps to Reproduce

Execute kernel test Phenotypes/tests/src/Kernel/TraitImporterRunTest.php. This test calls createTestFile() (in TripalCultivate Base) but with the required file fixture in Phenotypes module.

### Relevant log output

```shell
Drupal\Tests\trpcultivate_phenotypes\Kernel\TripalImporter\TraitImporterRunTest::testTraitImporterRunSimple
Unable to setup FILE  because cannot access Fixture file at /var/www/drupal/web/modules/contrib/TripalCultivate/tests/src/Traits/../Fixtures/TraitImporterFiles/simple_example.txt
Failed asserting that file "/var/www/drupal/web/modules/contrib/TripalCultivate/tests/src/Traits/../Fixtures/TraitImporterFiles/simple_example.txt" exists.
```

### PR DESCRIPTION
**Pull request by reynoldtan**
**Issue #58  Test Trait createTestFiles() could not reference file fixture in Phenotypes**

## Motivation

Enable test trait createTestFile() method to reference test Fixture files relative to the module it was called.

## What does this PR do?

- [x] Create a key in details array parameter that allows for specifying path to test Fixtures to reference.
- [x] Setup a test of using file fixture in createTestFile. 

### Automated Testing

- [x] TripalCultivateImporterTestTraitTest

### Manual Testing

No manual test.

1. Start a fresh docker image/container on this branch. **You can use the devcontainer approach OR the following commands:**
  ```
  cd ~/Dockers
  git clone https://github.com/TripalCultivate/TripalCultivate trpcultBase-PRNUM
  git checkout BRANCHNAME
  cd trpcultBase-PRNUM
  docker build --tag=trpcultivate-base:reviewPRNUM ./
  docker run --publish=80:80 -tid --name=basePRNUM --volume=`pwd`:/var/www/drupal/web/modules/contrib/TripalCultivate trpcultivate-base:reviewPRNUM
  ```

### CODE REVIEW

File: tests/src/Traits/TripalCultivateImporterTestTrait.php [hunk 1]
```diff
@@ -24,7 +24,9 @@ trait TripalCultivateImporterTestTrait {
    *         file in the temporary or public files directory.
    *     - content[string]: the content to copy into the file as a string
    *     - content[file]: an existing file in the fixtures directory to copy
-   *         the contents from
+   *         the contents from.
+   *     - content[fixturepath]: the path to Fixtures relative to the module the
+   *         method was called. Default to Fixtures directory of this module.
```
Comment (laceysanderson) [inline tests/src/Traits/TripalCultivateImporterTestTrait.php]: This should not be a relative path but rather an absolute path.
```suggestion
   *     - content[fixturepath]: the absolute path to Fixtures directory
   *         containing the test file. This should end with a '/'.
   *         Default to Fixtures directory of this module.
```

**Review by laceysanderson — COMMENTED** [review]
One small suggested change to the documentation but otherwise this looks good 👍 It's a small enough change that I don't think manual testing is needed.

**Review by laceysanderson — APPROVED** [review]
Perfect! Ready to merge!
